trigger:
- main

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    - script: |
        cd client
        npm ci
        npm run lint
        npm run build
      displayName: 'Build Client App'
    
    - script: |
        IF NOT EXIST "$(Build.ArtifactStagingDirectory)\client" mkdir "$(Build.ArtifactStagingDirectory)\client"
        IF EXIST "client\dist" (
          xcopy /Y /I /E "client\dist\*" "$(Build.ArtifactStagingDirectory)\client\"
        ) ELSE (
          echo "Warning: dist directory does not exist"
        )
      displayName: 'Copy client build artifacts'
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/client'
        artifactName: 'client-build'
    
    - script: |
        cd server
        npm ci
      displayName: 'Install Server Dependencies'
    
    - script: |
        IF NOT EXIST "$(Build.ArtifactStagingDirectory)\server" mkdir "$(Build.ArtifactStagingDirectory)\server"
        xcopy /Y /I /E "server\*" "$(Build.ArtifactStagingDirectory)\server\"
      displayName: 'Copy server files'
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/server'
        artifactName: 'server'