trigger:
- main

pool:
  name: Default

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    - script: |
        cd client
        npm ci
        npm run lint
        npm run build
      displayName: 'Build Client App'
    
    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/client
        cp -r client/dist/* $(Build.ArtifactStagingDirectory)/client/ || echo "Warning: dist directory may not exist"
      displayName: 'Copy client build artifacts'
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/client'
        artifactName: 'client-build'
    
    - script: |
        cd server
        npm ci
      displayName: 'Install Server Dependencies'
    
    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/server
        cp -r server/* $(Build.ArtifactStagingDirectory)/server/
      displayName: 'Copy server files'
      
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/server'
        artifactName: 'server'